// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/notblessy/skelago/model (interfaces: WelcomeUsecase)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/notblessy/skelago/model"
)

// MockWelcomeUsecase is a mock of WelcomeUsecase interface.
type MockWelcomeUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockWelcomeUsecaseMockRecorder
}

// MockWelcomeUsecaseMockRecorder is the mock recorder for MockWelcomeUsecase.
type MockWelcomeUsecaseMockRecorder struct {
	mock *MockWelcomeUsecase
}

// NewMockWelcomeUsecase creates a new mock instance.
func NewMockWelcomeUsecase(ctrl *gomock.Controller) *MockWelcomeUsecase {
	mock := &MockWelcomeUsecase{ctrl: ctrl}
	mock.recorder = &MockWelcomeUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWelcomeUsecase) EXPECT() *MockWelcomeUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWelcomeUsecase) Create(arg0 *model.Welcome) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWelcomeUsecaseMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWelcomeUsecase)(nil).Create), arg0)
}

// FindAll mocks base method.
func (m *MockWelcomeUsecase) FindAll(arg0 *model.WelcomeQuery) (*[]model.Welcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(*[]model.Welcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockWelcomeUsecaseMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockWelcomeUsecase)(nil).FindAll), arg0)
}
