// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/notblessy/skelago/model (interfaces: WelcomeRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/notblessy/skelago/model"
)

// MockWelcomeRepository is a mock of WelcomeRepository interface.
type MockWelcomeRepository struct {
	ctrl     *gomock.Controller
	recorder *MockWelcomeRepositoryMockRecorder
}

// MockWelcomeRepositoryMockRecorder is the mock recorder for MockWelcomeRepository.
type MockWelcomeRepositoryMockRecorder struct {
	mock *MockWelcomeRepository
}

// NewMockWelcomeRepository creates a new mock instance.
func NewMockWelcomeRepository(ctrl *gomock.Controller) *MockWelcomeRepository {
	mock := &MockWelcomeRepository{ctrl: ctrl}
	mock.recorder = &MockWelcomeRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWelcomeRepository) EXPECT() *MockWelcomeRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWelcomeRepository) Create(arg0 *model.Welcome) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockWelcomeRepositoryMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWelcomeRepository)(nil).Create), arg0)
}

// FindAll mocks base method.
func (m *MockWelcomeRepository) FindAll(arg0 *model.WelcomeQuery) (*[]model.Welcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", arg0)
	ret0, _ := ret[0].(*[]model.Welcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockWelcomeRepositoryMockRecorder) FindAll(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockWelcomeRepository)(nil).FindAll), arg0)
}

// FindByID mocks base method.
func (m *MockWelcomeRepository) FindByID(arg0 string) (*model.Welcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*model.Welcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockWelcomeRepositoryMockRecorder) FindByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockWelcomeRepository)(nil).FindByID), arg0)
}
